apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JBderLeuchtturm/Data-Engineering
    targetRevision: main
    path: namespaces

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true